version: 2
registries:
  interlok:
    type: maven-repository
    url: https://nexus.adaptris.net/nexus/content/groups/interlok
    username: jenkins
    password: ${{secrets.NEXUS_PASSWORD}}
  public:
    type: maven-repository
    url: https://nexus.adaptris.net/nexus/content/groups/public
    username: jenkins
    password: ${{secrets.NEXUS_PASSWORD}}

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - "interlok"
      - "public"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    reviewers:
      - quotidian-ennui
      - mcwarman
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    reviewers:
      - quotidian-ennui
      - mcwarman
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella